name: Build and publish images

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  release-image:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: 
          - context: build-bookworm-slim
            image_name: build-bookworm-slim
    uses: kea-run/base-images/.github/workflows/build-image.yaml@master
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      context: ${{ matrix.image.context }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

