name: Build and publish images

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  release-image:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: 
          - name: build-bookworm-slim
            context: build-bookworm-slim

    uses: kea-run/base-images/.github/workflows/build-image.yaml@master
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dir: ${{ matrix.image.context }}
      image_name: ${{ matrix.image.name }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

