name: Build and publish images

on:
  push:
    branches: ["master"]
    paths:
      - 'build-bookworm-slim/**'
      - 'run-bookworm-slim/**'

  workflow_dispatch:

jobs:
  release-image:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: 
          - name: build-bookworm-slim
            context: build-bookworm-slim
          - name: run-bookworm-slim
            context: run-bookworm-slim

    uses: kea-run/base-images/.github/workflows/_build-image.yaml@master
    with:
      context: ${{ matrix.image.context }}
      image_name: ${{ matrix.image.name }}
      dockerhub_repo: kearun
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

