name: Create and publish Docker images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      context:
        type: string
        required: true
      image_name:
        type: string
        required: true
      dockerhub_username:
        type: string
        required: true
    secrets:
      dockerhub_token:
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.build_metadata.outputs.package_name_full_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the ghcr registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the dockerhub registry
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ inputs.dockerhub_username}}
          password: ${{ secrets.dockerhub_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=ref,event=branch
            type=sha,format=long,prefix=
            type=sha,format=short,prefix=
            
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
            ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.16.0
        platforms: linux/amd64,linux/arm64
        with:
          context: ${{ inputs.context }}
          file: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
